name: Issue Created Workflow

on:
  issues:
    types: [opened]

jobs:
  comment_on_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Add comment to the issue
      uses: peter-evans/comment-on-issue@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: 'Issue créée'
