name: Issue Created Workflow

on:
  issues:
    types: [opened]

jobs:
  comment_on_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Ajouter un commentaire à l'issue
      if: ${{on.ISSUES.types == 'opened'}}  
        run: echo "Ticket erreur ouvert "
        
