name: Manual Workflow with Dependencies

on:
  workflow_dispatch:  # Permet le lancement manuel du workflow

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Exécuter le Job 1
        run: echo "🚀 Job 1 exécuté !"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Attend que job1 soit terminé avant de se lancer
    steps:
      - name: Exécuter le Job 2
        run: echo "✅ Job 2 exécuté après Job 1 !"
